services:
  db:
    container_name: timetable
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timetable
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5427:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db:
